use crate::topology::const_Simplex;

pub const S1: [&const_Simplex;6] = [
	&const_Simplex{value: &[1], dimension: 0},
	&const_Simplex{value: &[2], dimension: 0},
	&const_Simplex{value: &[3], dimension: 0},
	&const_Simplex{value: &[1,2], dimension: 1},
	&const_Simplex{value: &[2,3], dimension: 1},
	&const_Simplex{value: &[1,3], dimension: 1},
];

// https://math.jhu.edu/~jmb/note/rp2tri.pdf
pub const RP2: [&const_Simplex;31] = [
	&const_Simplex{value: &[1], dimension: 0},
	&const_Simplex{value: &[2], dimension: 0},
	&const_Simplex{value: &[3], dimension: 0},
	&const_Simplex{value: &[4], dimension: 0},
	&const_Simplex{value: &[5], dimension: 0},
	&const_Simplex{value: &[6], dimension: 0},
	&const_Simplex{value: &[1,2], dimension: 1},
	&const_Simplex{value: &[1,3], dimension: 1},
	&const_Simplex{value: &[1,4], dimension: 1},
	&const_Simplex{value: &[1,5], dimension: 1},
	&const_Simplex{value: &[1,6], dimension: 1},
	&const_Simplex{value: &[2,3], dimension: 1},
	&const_Simplex{value: &[2,4], dimension: 1},
	&const_Simplex{value: &[2,5], dimension: 1},
	&const_Simplex{value: &[2,6], dimension: 1},
	&const_Simplex{value: &[3,4], dimension: 1},
	&const_Simplex{value: &[3,5], dimension: 1},
	&const_Simplex{value: &[3,6], dimension: 1},
	&const_Simplex{value: &[4,5], dimension: 1},
	&const_Simplex{value: &[4,6], dimension: 1},
	&const_Simplex{value: &[5,6], dimension: 1},
	&const_Simplex{value: &[1,3,4], dimension: 2},
	&const_Simplex{value: &[1,2,4], dimension: 2},
	&const_Simplex{value: &[1,2,6], dimension: 2},
	&const_Simplex{value: &[1,3,5], dimension: 2},
	&const_Simplex{value: &[1,5,6], dimension: 2},
	&const_Simplex{value: &[2,3,6], dimension: 2},
	&const_Simplex{value: &[2,3,5], dimension: 2},
	&const_Simplex{value: &[2,4,5], dimension: 2},
	&const_Simplex{value: &[3,4,6], dimension: 2},
	&const_Simplex{value: &[4,5,6], dimension: 2},
];

// https://orangewire.xyz/mathematics/2022/03/25/simplicial,homology.html
pub const T2: [&const_Simplex;42] = [
	&const_Simplex{value: &[1], dimension: 0},
	&const_Simplex{value: &[2], dimension: 0},
	&const_Simplex{value: &[3], dimension: 0},
	&const_Simplex{value: &[4], dimension: 0},
	&const_Simplex{value: &[5], dimension: 0},
	&const_Simplex{value: &[6], dimension: 0},
	&const_Simplex{value: &[7], dimension: 0},
	&const_Simplex{value: &[1,2], dimension: 1},
	&const_Simplex{value: &[1,3], dimension: 1},
	&const_Simplex{value: &[1,4], dimension: 1},
	&const_Simplex{value: &[1,5], dimension: 1},
	&const_Simplex{value: &[1,6], dimension: 1},
	&const_Simplex{value: &[1,7], dimension: 1},
	&const_Simplex{value: &[2,3], dimension: 1},
	&const_Simplex{value: &[2,4], dimension: 1},
	&const_Simplex{value: &[2,5], dimension: 1},
	&const_Simplex{value: &[2,6], dimension: 1},
	&const_Simplex{value: &[2,7], dimension: 1},
	&const_Simplex{value: &[3,4], dimension: 1},
	&const_Simplex{value: &[3,5], dimension: 1},
	&const_Simplex{value: &[3,6], dimension: 1},
	&const_Simplex{value: &[3,7], dimension: 1},
	&const_Simplex{value: &[4,5], dimension: 1},
	&const_Simplex{value: &[4,6], dimension: 1},
	&const_Simplex{value: &[4,7], dimension: 1},
	&const_Simplex{value: &[5,6], dimension: 1},
	&const_Simplex{value: &[5,7], dimension: 1},
	&const_Simplex{value: &[6,7], dimension: 1},
	&const_Simplex{value: &[1,2,4], dimension: 2},
	&const_Simplex{value: &[1,2,6], dimension: 2},
	&const_Simplex{value: &[1,3,4], dimension: 2},
	&const_Simplex{value: &[1,3,7], dimension: 2},
	&const_Simplex{value: &[1,5,6], dimension: 2},
	&const_Simplex{value: &[1,5,7], dimension: 2},
	&const_Simplex{value: &[2,3,5], dimension: 2},
	&const_Simplex{value: &[2,3,7], dimension: 2},
	&const_Simplex{value: &[2,4,5], dimension: 2},
	&const_Simplex{value: &[2,6,7], dimension: 2},
	&const_Simplex{value: &[3,4,6], dimension: 2},
	&const_Simplex{value: &[3,5,6], dimension: 2},
	&const_Simplex{value: &[4,5,7], dimension: 2},
	&const_Simplex{value: &[4,6,7], dimension: 2},
];
